config/routes.rb
PollywogRanchRailsRuby003::Application.routes.draw do

resources :frogs, :tadpoles, :ponds

post '/evolve' => 'tadpoles#evolve'

root :to => 'application#index'

  

end

app/models/frog.rb
class Frog < ActiveRecord::Base
  has_many :tadpoles
  belongs_to :pond
end

app/models/pond.rb
class Pond < ActiveRecord::Base
  has_many :frogs
  has_many :tadpoles
end

app/models/tadpole.rb
class Tadpole < ActiveRecord::Base
  belongs_to :frog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def index
end
#   ####pasted from sinatra
#     configure :development do
#     register Sinatra::Reloader
#   end

#   set :public_folder, Proc.new { File.join(root, "../assets/") }
#   set :views, Proc.new { File.join(root, "../views/") }

# ####### Root #######

#   get '/'  do
#     erb :index
#   end

#   ####end pasted from sinatra
end

app/controllers/frog_controller.rb
class FrogController < ApplicationController
  # get '/frogs'  do
  #   # Write the code to get all frogs 
  #   # and send them to the index view listing all frogs.
  #   @frogs = Frog.all
  #   erb :'frogs/index'
  # end

  # post '/frogs' do
  #   # Write the code to save new frogs 
  #   # and redirect to the index view listing all frogs.
  #   Frog.create(params)
  #   redirect 'frogs'
  # end

  # get '/frogs/new' do
  #   @ponds = Pond.all
  #   # Write the code to send to the new form view.
  #   erb :'frogs/new'

  # end

  # get '/frogs/:id' do
  #   # binding.pry
  #   @frog = Frog.find(params[:id])
  #   erb :'frogs/show'
  #   # Write the code to find the correct frog
  #   # by id given in the url.
  #   # Then send them to the show view.

  # end

  # get '/frogs/:id/edit' do
  #   @frog = Frog.find(params[:id])
  #   erb :'frogs/edit'
  #   # Write the code to find the correct frog
  #   # by id given in the url.
  #   # Then send them to edit form view.

  # end

  # post '/frogs/:id/update' do
  #   frog = Frog.find(params[:id])
  #   frog.name = params[:name]
  #   frog.color = params[:color]
  #   frog.lives = params[:lives]
  #   frog.save
  #   redirect 'frogs'
  #   # Write the code to find the correct frog
  #   # and set it's attributes and save.
  #   # Then redirect to the index view listing all frogs.

  # end

  # get '/frogs/:id/destroy' do
  #   frog = Frog.find(params[:id])
  #   frog.destroy
  #   redirect 'frogs'
  #   # Write the code to find the correct frog
  #   # and destroy it.
  #   # Then redirect to the index view listing all frogs.

  # end

  # get '/frogs/:id/tadpoles/new' do
  #   @frog = Frog.find(params[:id])
  #   redirect '../tadpoles/index'
  #   # Write the code to find the correct frog
  #   # and redirect to new tadpole form view
    
  # end
end

app/controllers/frogs_controller.rb
require 'pry'
class FrogsController < ApplicationController
 
  def index
    @frogs = Frog.all
  end

  def show
    @frog = Frog.find(params[:id])
    @pond = @frog.pond
  end

  def new
    @ponds = Pond.all
  end

  def create
    binding.pry
    frog = Frog.create(:name => params[:frog][:name], :color => params[:frog][:color], :pond_id => params[:pond_id])
    redirect_to action: "index"  
  end

  def edit
    @ponds = Pond.all
  end

  def update
    frog = Frog.find(params[:id])
    frog.name = params[:frog][:name]
    frog.color = params[:frog][:color]
    frog.pond_id = params[:pond_id]
    frog.save
    redirect_to action: "index"
  end

  def destroy
    frog = Frog.find(params[:id])
    frog.destroy
    redirect_to action: "index"
  end 
end

app/controllers/ponds_controller.rb
require 'pry'
class PondsController < ApplicationController

  def index
    @ponds = Pond.all
  end

  def show
    @pond = Pond.find(params[:id])
  end

  def new
  end

  def create
    pond = Pond.create(:name => params[:pond][:name], :water_type => params[:pond][:water_type])
    redirect_to action: "index"  
  end

  def edit

  end

  def update
    pond = Pond.find(params[:id])
    pond.name = params[:pond][:name]
    pond.water_type = params[:pond][:water_type]
    pond.save
    redirect_to action: "index"
  end

  def destroy
    pond = Pond.find(params[:id])
    pond.destroy
    redirect_to action: "index"
  end 
  
end

app/controllers/tadpole_controller.rb
class TadpoleController < ApplicationController
  get '/tadpoles'  do
    # Write the code to get all tadpoles 
    # and send them to the index view listing all tadpoles.
    @tadpoles = Tadpole.all
    erb :'tadpoles/index'
  end

  post '/tadpoles' do
    # Write the code to create a new tadpole
    # using the attributes included from the new form view.
    # Also set the frog parent using the passed frog_id atribute.
    # Then save and redirect to the index view listing all tadpoles.
    tadpole = Tadpole.create(params)
    redirect 'tadpoles'
    
  end

  get '/tadpoles/:id' do
    @tadpole = Tadpole.find(params[:id])
    erb :'tadpoles/show'
    # Write the code to find the correct tadpole
    # by id given in the url.
    # Then send them to the show view.

  end

  get '/tadpoles/:id/edit' do
    # Write the code to find the correct tadpole
    # by id given in the url.
    # Then send them to edit form view.
    @tadpole = Tadpole.find(params[:id])
    erb :'tadpoles/edit'
  end

  post '/tadpoles/:id/update' do
    tadpole = Tadpole.find(params[:id])
    tadpole.name = params[:name]
    tadpole.color = params[:color]
    tadpole.save
    redirect 'tadpoles'
    # Write the code to find the correct tadpole
    # and set it's attributes and save.
    # Then redirect to the index view listing all tadpoles.

  end

  get '/tadpoles/:id/destroy' do
    tadpole = Tadpole.find(params[:id])
    tadpole.destroy
    redirect 'tadpoles'
    # Write the code to find the correct tadpole
    # and destroy it.
    # Then redirect to the index view listing all tadpoles.

  end

  get '/tadpoles/:id/evolve' do
    tadpole = Tadpole.find(params[:id])
    frog = Frog.new
    frog.name = tadpole.name
    frog.color = tadpole.color
    frog.pond = Frog.find(tadpole.frog_id).pond
    frog.save
    tadpole.destroy
    redirect 'tadpoles'
    # Write the code to find the correct tadpole
    # by id given in the url and store it temporarily.
    # Create a new frog and pass the attributes of the 
    # tadpole into the frog that it is becoming.
    # Then save the new frog and destroy the old tadpole.
    # Then redirect to the index view listing all tadpoles.

  end

end
end

app/controllers/tadpoles_controller.rb
require 'pry'
class TadpolesController < ApplicationController

  def index
      @tadpoles = Tadpole.all
  end

  def show
    @tadpole = Tadpole.find(params[:id])
  end

  def new
    @frogs = Frog.all
  end

  def create
    frog = Frog.find(params[:frog_id])
    tadpole = Tadpole.create(:name => params[:tadpole][:name], :color => frog.color, :frog_id => params[:frog_id])
    redirect_to action: "index"  
  end

  def edit
    @frogs = Frog.all
    @ponds = Pond.all
  end

  def update
    tadpole = Tadpole.find(params[:id])
    tadpole.name = params[:tadpole][:name]
    tadpole.color = params[:tadpole][:color]
    tadpole.frog_id = params[:frog_id]
    tadpole.save
    redirect_to action: "index"
  end

  def destroy
    tadpole = Tadpole.find(params[:id])
    tadpole.destroy
    redirect_to action: "index"
  end 

  def evolve
    tadpole = Tadpole.find(params[:id])
    parent = Frog.find(tadpole.frog_id)
    newfrog = Frog.create(:name => tadpole.name, :color => tadpole.color, :pond_id => parent.pond_id)
    tadpole.destroy
    redirect_to action: "index"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frog_helper.rb
module FrogHelper
end

app/helpers/pond_helper.rb
module PondHelper
end

app/helpers/tadpole_helper.rb
module TadpoleHelper
end

app/views/application/index.html.erb
<%= render template: "layouts/header" %>

<h1>Welcome to Pollywog Ranch</h1>
<p>Please select from the choices above.</p>

<%= render template: "layouts/footer" %>

app/views/frogs/edit.html.erb
<%= render template: "layouts/header" %>

<%= form_for(Frog.find(params[:id])) do |f| %>
  Frog Name: <%= f.text_field :name %><br />
  Frog Color: <%= f.text_field :color %><br />
  
  <!-- Railsify this section -->
  <label for="lives">Lives</label>
  <select id="lives" name="pond_id">
    <% @ponds.each do |pond| %>
      <option value="<%= pond.id %>"><%= pond.name %></option>
    <% end %>
    <br>
  </select>
  <!-- end section -->

  <%= f.submit %>
<% end %>

<%= link_to 'Back', ponds_path %>
<%= render template: "layouts/footer" %>

app/views/frogs/index.html.erb
<%= render template: "layouts/header" %>

<h1>Frogs</h1>

<% @frogs.each do |frog| %>
<%= link_to frog.name, frog %> 
<br>
<br>
<% end %>

<%= link_to "Create a New frog", {:action=>"new", :controller=>"frogs"} %>

<%= render template: "layouts/footer" %>

app/views/frogs/new.html.erb
<%= render template: "layouts/header" %>

<%= form_for(Frog.new) do |f| %>
  Frog Name: <%= f.text_field :name %><br />
  Frog Color: <%= f.text_field :color %><br />
  <!-- I want to convert this section to the rails way later -->
  <label for="lives">Lives</label>
  <select id="lives" name="pond_id">
    <% @ponds.each do |pond| %>
      <option value="<%= pond.id %>"><%= pond.name %></option>
    <% end %>
  </select>
  <!-- end section -->

  <br>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', ponds_path %>
<%= render template: "layouts/footer" %>

app/views/frogs/show.html.erb
<%= render template: "layouts/header" %>

<h1><%= @frog.name %></h1>

<h2>Pond</h2>
<%= link_to @pond.name, @pond %>

<h2>Tadpoles</h2>
<% @frog.tadpoles.each do |tadpole| %>
<p>
<%= link_to tadpole.name, tadpole %>
</p>
<br>
<% end %>
<%= link_to "Create a New Tadpole", {:action=>"new", :controller=>"tadpoles"} %>
<br>
<%= link_to "Edit This Frog", {:action=>"edit", :controller=>"frogs"} %>
<br>
<%= button_to "Destroy This Frog", @frog, method: "delete" %>
<br>

<%= link_to 'Back', ponds_path %>
<%= render template: "layouts/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PollywogRanchRailsRuby003</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/footer.html.erb
</body>
</html>

app/views/layouts/header.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Pollywog Ranch</title>
    <link rel="stylesheet" href="/css/style.css">
  </head>
  <body>
    <nav>
      <a href="/ponds">Ponds</a> | 
      <a href="/frogs">Frogs</a> | 
      <a href="/tadpoles">Tadpoles</a>
    </nav>

app/views/ponds/edit.html.erb
<%= render template: "layouts/header" %>

<%= form_for(Pond.find(params[:id])) do |p| %>
  Pond Name: <%= p.text_field :name %><br />
  Water Type : <%= p.text_field :water_type %><br />
  <%= p.submit %>
<% end %>

<%= link_to 'Back', ponds_path %>
<%= render template: "layouts/footer" %>

app/views/ponds/index.html.erb
<%= render template: "layouts/header" %>

<h1>Ponds</h1>

<% @ponds.each do |pond| %>
<%= link_to pond.name, pond %> 
<br>
<br>
<% end %>

<%= link_to "Create a New Pond", {:action=>"new", :controller=>"ponds"} %>

<%= render template: "layouts/footer" %>

app/views/ponds/new.html.erb
<%= form_for(Pond.new) do |p| %>
  Pond Name: <%= p.text_field :name %><br />
  Water Type : <%= p.text_field :water_type %><br />
  <%= p.submit %>
<% end %>

app/views/ponds/show.html.erb
<%= render template: "layouts/header" %>

<h1><%= @pond.name %></h1>

<h2>Water Type</h2>
<%= @pond.water_type %>

<h2>Frogs & Tadpoles</h2>
<h3>Frog</h3>
<% @pond.frogs.each do |frog| %>
<p>
<%= link_to frog.name, frog %>
</p>
<br>
<h3>Tadpoles</h3>
<% frog.tadpoles.each do |tp| %>
<%= link_to tp.name, tp %>
<br>
<% end %>
<% end %>

<%= link_to "Edit This Pond", {:action=>"edit", :controller=>"ponds"} %>
<br>
<%= button_to "Destroy This Pond", @pond, method: "delete" %>

<%= link_to 'Back', ponds_path %>
<%= render template: "layouts/footer" %>

app/views/tadpoles/edit.html.erb
<%= render template: "layouts/header" %>

<%= form_for(Tadpole.find(params[:id])) do |f| %>
  Tadpole Name: <%= f.text_field :name %><br />
  Tadpole Color: <%= f.text_field :color %><br />
  <!-- Railsify this section -->
  <label for="parent">Parent</label>
  <select id="parent" name="frog_id">
    <% @frogs.each do |frog| %>
      <option value="<%= frog.id %>"><%= frog.name %></option>
    <% end %>
    <br>
  </select>
  <!-- end section -->

  <%= f.submit %>
<% end %>

<%= link_to 'Back', tadpoles_path %>
<%= render template: "layouts/footer" %>

app/views/tadpoles/index.html.erb
<%= render template: "layouts/header" %>

<h1>Tadpoles</h1>

<% @tadpoles.each do |tadpole| %>
<%= link_to tadpole.name, tadpole %> 
<br>
<br>
<% end %>

<%= link_to "Create a New Tadpole", {:action=>"new", :controller=>"tadpoles"} %>

<%= render template: "layouts/footer" %>

app/views/tadpoles/new.html.erb
<%= render template: "layouts/header" %>

<%= form_for(Tadpole.new) do |t| %>
  Tadpole Name: <%= t.text_field :name %><br />
  
  <!-- I want to convert this section to the rails way later -->
  <label for="parent">Parent</label>
  <select id="parent" name="frog_id">
    <% @frogs.each do |frog| %>
      <option value="<%= frog.id %>"><%= frog.name %></option>
    <% end %>
  </select>
  <!-- end section -->

  <br>
  <%= t.submit %>
<% end %>

<%= link_to 'Back', tadpoles_path %>
<%= render template: "layouts/footer" %>

app/views/tadpoles/show.html.erb
<%= render template: "layouts/header" %>

<h1><%= @tadpole.name %></h1>

<h2>Parent</h2>
<%= link_to @tadpole.frog.name, @tadpole.frog %>
<br>
<br>
<%= link_to "Edit This tadpole", {:action=>"edit", :controller=>"tadpoles"} %>
<br>
<%= button_to "Destroy This tadpole", @tadpole, method: "delete" %>
<br>
<%= button_to "EVOLVE THIS TADPOLE", {:action => "evolve", :id => @tadpole.id}, method: "post" %>

<%= link_to 'Back', tadpoles_path %>
<%= render template: "layouts/footer" %>